# Generated by Django 3.1.7 on 2021-02-24 07:52

import apps.user.validators
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['username'])),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('birthday', models.DateField(validators=[apps.user.validators.minimum_age])),
            ],
        ),
    ]
