# Generated by Django 3.1.4 on 2021-03-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210318_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date__year', '-published_date__day', '-published_date__hour', '-published_date__minute', '-published_date__second']},
        ),
    ]
