# Generated by Django 3.1.4 on 2021-03-31 12:29

import apps.post.models.post
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210330_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.post.models.post.get_upload_path),
        ),
    ]
