# Generated by Django 3.1.4 on 2021-03-17 10:35

import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, unique=True, validators=[apps.user.validators.mobile_validator, apps.user.validators.mobile_len_validator]),
        ),
    ]
