# Generated by Django 3.1.4 on 2021-03-18 06:42

import apps.user.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210317_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile.svg', upload_to=apps.user.models.profile.get_upload_path),
        ),
    ]
