# Generated by Django 3.1.4 on 2021-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
